spring:
  datasource:
    url: jdbc:postgresql://172.28.141.23/sweatter
    username: beenavigator
    password: beenavigator123
    platform: postgres
  jpa:
    generate-ddl: true
    database: POSTGRESQL
